"""initial schema (SQLite)

Tideline moved from Postgres to SQLite in September 2026 (docs/decisions/0005),
so the migration history starts again here. Times are stored as naive UTC;
tideline.db.models.UTCDateTime adds the time zone back when reading.

Revision ID: 8ee41989e4ea
Revises: 
Create Date: 2026-09-17 22:29:49.249813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ee41989e4ea'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('domain', sa.String(length=253), nullable=False),
    sa.Column('urls', sa.JSON(), nullable=False),
    sa.Column('expected_text', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sites')),
    sa.UniqueConstraint('domain', name=op.f('uq_sites_domain'))
    )
    op.create_table('checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('interval_seconds', sa.Integer(), nullable=False),
    sa.Column('config', sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.CheckConstraint("kind IN ('uptime', 'content', 'tls', 'domain', 'dns', 'email_auth', 'links', 'form')", name=op.f('ck_checks_kind_valid')),
    sa.CheckConstraint('interval_seconds > 0', name=op.f('ck_checks_interval_positive')),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_checks_site_id_sites'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_checks')),
    sa.UniqueConstraint('site_id', 'key', name=op.f('uq_checks_site_id'))
    )
    op.create_table('daily_rollups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('results', sa.Integer(), nullable=False),
    sa.Column('ok_results', sa.Integer(), nullable=False),
    sa.Column('uptime_checks', sa.Integer(), nullable=False),
    sa.Column('uptime_ok', sa.Integer(), nullable=False),
    sa.Column('uptime_percent', sa.Float(), nullable=True),
    sa.Column('p50_ms', sa.Integer(), nullable=True),
    sa.Column('p95_ms', sa.Integer(), nullable=True),
    sa.Column('incidents_opened', sa.Integer(), nullable=False),
    sa.Column('downtime_seconds', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_daily_rollups_site_id_sites'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_rollups')),
    sa.UniqueConstraint('site_id', 'day', name=op.f('uq_daily_rollups_site_id'))
    )
    with op.batch_alter_table('daily_rollups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_rollups_site_id'), ['site_id'], unique=False)

    op.create_table('dns_baselines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('records', sa.JSON(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_dns_baselines_site_id_sites'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dns_baselines'))
    )
    op.create_table('check_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('check_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=4), nullable=False),
    sa.Column('detail', sa.JSON(), server_default=sa.text("'{}'"), nullable=False),
    sa.CheckConstraint("status IN ('ok', 'warn', 'fail')", name=op.f('ck_check_results_status_valid')),
    sa.ForeignKeyConstraint(['check_id'], ['checks.id'], name=op.f('fk_check_results_check_id_checks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_check_results'))
    )
    with op.batch_alter_table('check_results', schema=None) as batch_op:
        batch_op.create_index('ix_check_results_check_id_started_at', ['check_id', 'started_at'], unique=False)

    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('check_id', sa.Integer(), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('last_alerted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("severity IN ('warning', 'critical')", name=op.f('ck_incidents_severity_valid')),
    sa.ForeignKeyConstraint(['check_id'], ['checks.id'], name=op.f('fk_incidents_check_id_checks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incidents'))
    )
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incidents_check_id'), ['check_id'], unique=False)
        batch_op.create_index('uq_incidents_one_open_per_check', ['check_id'], unique=True, sqlite_where=sa.text('resolved_at IS NULL'))

    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.CheckConstraint("kind IN ('open', 'escalated', 'reminder', 'resolved')", name=op.f('ck_alerts_kind_valid')),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_alerts_incident_id_incidents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerts'))
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_incident_id'), ['incident_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_incident_id'))

    op.drop_table('alerts')
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_index('uq_incidents_one_open_per_check', sqlite_where=sa.text('resolved_at IS NULL'))
        batch_op.drop_index(batch_op.f('ix_incidents_check_id'))

    op.drop_table('incidents')
    with op.batch_alter_table('check_results', schema=None) as batch_op:
        batch_op.drop_index('ix_check_results_check_id_started_at')

    op.drop_table('check_results')
    op.drop_table('dns_baselines')
    with op.batch_alter_table('daily_rollups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_rollups_site_id'))

    op.drop_table('daily_rollups')
    op.drop_table('checks')
    op.drop_table('sites')
    # ### end Alembic commands ###
