"""daily rollups

Revision ID: 1bc79a4a871b
Revises: 281b9d62bb5d
Create Date: 2026-09-17 16:51:14.982750

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1bc79a4a871b"
down_revision: Union[str, Sequence[str], None] = "281b9d62bb5d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "daily_rollups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("results", sa.Integer(), nullable=False),
        sa.Column("ok_results", sa.Integer(), nullable=False),
        sa.Column("uptime_checks", sa.Integer(), nullable=False),
        sa.Column("uptime_ok", sa.Integer(), nullable=False),
        sa.Column("uptime_percent", sa.Float(), nullable=True),
        sa.Column("p50_ms", sa.Integer(), nullable=True),
        sa.Column("p95_ms", sa.Integer(), nullable=True),
        sa.Column("incidents_opened", sa.Integer(), nullable=False),
        sa.Column("downtime_seconds", sa.Integer(), nullable=False),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["site_id"],
            ["sites.id"],
            name=op.f("fk_daily_rollups_site_id_sites"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_daily_rollups")),
        sa.UniqueConstraint("site_id", "day", name=op.f("uq_daily_rollups_site_id")),
    )
    op.create_index(op.f("ix_daily_rollups_site_id"), "daily_rollups", ["site_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_daily_rollups_site_id"), table_name="daily_rollups")
    op.drop_table("daily_rollups")
    # ### end Alembic commands ###
